INSERT INTO Filters(
    filter_no,
    filter_name
) VALUES 

    (1,'Location'),
    (2,'Small Group'),
    (3,'Reoccuring'),
    (4,'TA Available');

INSERT INTO Course(
    course_no,
    course_code,
    course_name
)
VALUES
(1000, 'CSCI', 'Computer Science as a Field of Work and Study'),
(1200, 'CSCI', 'Introduction to Computational Thinking'),
(1300, 'CSCI', 'Computer Science 1: Starting Computing'),
(2270, 'CSCI', 'Computer Science 2: Data Structures'),
(2275, 'CSCI', 'Programming and Data Structures'),
(2400, 'CSCI', 'Computer Systems'),
(2750, 'CSCI', 'Computing, Ethics and Society'),
(2820, 'CSCI', 'Linear Algebra with Computer Science Applications'),
(2824, 'CSCI', 'Discrete Structures'),
(2830, 'CSCI', 'Special Topics in Computer Science'),
(2834, 'CSCI', 'Discrete Structures Workgroup'),
(2897, 'CSCI', 'Calculating Biological Quantities'),
(2900, 'CSCI', 'Lower Division, Undergraduate Level Independent Study'),
(3002, 'CSCI', 'Fundamentals of Human Computer Interaction'),
(3010, 'CSCI', 'Intensive Programming Workshop'),
(3022, 'CSCI', 'Introduction to Data Science with Probability and Statistics'),
(3090, 'CSCI', 'Introduction to Quantum Computing'),
(3100, 'CSCI', 'Software and Society'),
(3104, 'CSCI', 'Algorithms'),
(3112, 'CSCI', 'Professional Development in Computer Science'),
(3150, 'CSCI', 'Universal Design for Digital Media'),
(3155, 'CSCI', 'Principles of Programming Languages'),
(3202, 'CSCI', 'Introduction to Artificial Intelligence'),
(3287, 'CSCI', 'Design and Analysis of Database Systems'),
(3302, 'CSCI', 'Introduction to Robotics'),
(3308, 'CSCI', 'Software Development Methods and Tools'),
(3352, 'CSCI', 'Biological Networks'),
(3403, 'CSCI', 'Introduction to CyberSecurity for a Converged World'),
(3434, 'CSCI', 'Theory of Computation'),
(3656, 'CSCI', 'Numerical Computation'),
(3702, 'CSCI', 'Cognitive Science'),
(3753, 'CSCI', 'Design and Analysis of Operating Systems'),
(3832, 'CSCI', 'Natural Language Processing'),
(4022, 'CSCI', 'Advanced Data Science'),
(4113, 'CSCI', 'Linux System Administration'),
(4114, 'CSCI', 'Practical Algorithmic Complexity'),
(4118, 'CSCI', 'Software Engineering for Scientists'),
(4122, 'CSCI', 'Information Visualization'),
(4133, 'CSCI', 'Fundamentals of Computer Security'),
(4200, 'CSCI', 'Introduction to Wireless Systems'),
(4229, 'CSCI', 'Computer Graphics'),
(4239, 'CSCI', 'Advanced Computer Graphics'),
(4240, 'CSCI', 'Introduction to Blockchain'),
(4253, 'CSCI', 'Datacenter Scale Computing - Methods, Systems and Techniques'),
(4273, 'CSCI', 'Network Systems'),
(4302, 'CSCI', 'Advanced Robotics'),
(4303, 'CSCI', 'Cybersecurity Club Companion Course'),
(4308, 'CSCI', 'Software Engineering Project 1'),
(4313, 'CSCI', 'Concurrent Programming'),
(4314, 'CSCI', 'Dynamic Models in Biology'),
(4318, 'CSCI', 'Software Engineering Project 2'),
(4328, 'CSCI', 'Software Project Management and Mentoring'),
(4338, 'CSCI', 'Software Project Management'),
(4348, 'CSCI', 'Startup Essentials: Entrepreneurial Projects in Computing'),
(4358, 'CSCI', 'Entrepreneurial Projects II'),
(4413, 'CSCI', 'Computer Security and Ethical Hacking'),
(4446, 'CSCI', 'Chaotic Dynamics'),
(4448, 'CSCI', 'Object-Oriented Analysis and Design'),
(4502, 'CSCI', 'Data Mining'),
(4555, 'CSCI', 'Compiler Construction'),
(4576, 'CSCI', 'High-Performance Scientific Computing'),
(4593, 'CSCI', 'Computer Organization'),
(4616, 'CSCI', 'Introduction to Virtual Reality'),
(4622, 'CSCI', 'Machine Learning'),
(4753, 'CSCI', 'Computer Performance Modeling'),
(4802, 'CSCI', 'Data Science Team Companion Course'),
(4809, 'CSCI', 'Computer Animation'),
(4830, 'CSCI', 'Special Topics in Computer Science'),
(4831, 'CSCI', 'Special Topics in Algorithms'),
(4849, 'CSCI', 'Input, Interaction, and Accessibility'),
(4889, 'CSCI', 'Interactive Machine Learning for Customizable and Expressive Interfaces'),
(4900, 'CSCI', 'Upper Division, Undergraduate Level Independent Study'),
(4950, 'CSCI', 'Senior Thesis'),
(4960, 'CSCI', 'Computer Science Honors Thesis'),
(5000, 'CSCI', 'Introduction to the Computer Science Research-Based MS Program'),
(5010, 'CSCI', 'Fundamentals of Data Communication'),
(5020, 'CSCI', 'Fundamentals of Network Programming'),
(5030, 'CSCI', 'Fundamentals of System Administration and Virtualization'),
(5040, 'CSCI', 'Professional Masters Project 1'),
(5050, 'CSCI', 'Professional Masters Project 2'),
(5100, 'CSCI', 'Computer Science Colloquium'),
(5113, 'CSCI', 'Linux System Administration'),
(5114, 'CSCI', 'Practical Algorithmic Complexity'),
(5135, 'CSCI', 'Computer-Aided Verification'),
(5140, 'CSCI', 'CLASIC Capstone'),
(5160, 'CSCI', 'Introduction to Enterprise Networks'),
(5170, 'CSCI', 'IP Routing Protocols and Policies'),
(5180, 'CSCI', 'Network Management and Automation'),
(5190, 'CSCI', 'Voice Over IP: Voice Network Design and Implementation'),
(5200, 'CSCI', 'Introduction to Wireless Systems'),
(5220, 'CSCI', 'Wireless Local Area Networks'),
(5229, 'CSCI', 'Computer Graphics'),
(5230, 'CSCI', 'Wireless Systems Lab'),
(5239, 'CSCI', 'Advanced Computer Graphics'),
(5240, 'CSCI', 'Introduction to Blockchain'),
(5253, 'CSCI', 'Datacenter Scale Computing - Methods, Systems and Techniques'),
(5254, 'CSCI', 'Convex Optimization and Its Applications'),
(5260, 'CSCI', 'Datacenter Networks'),
(5270, 'CSCI', 'IP Network Design'),
(5273, 'CSCI', 'Network Systems'),
(5280, 'CSCI', 'Software-Defined Networking'),
(5302, 'CSCI', 'Advanced Robotics'),
(5303, 'CSCI', 'Cybersecurity Club Companion Course'),
(5313, 'CSCI', 'Concurrent Programming'),
(5314, 'CSCI', 'Dynamic Models in Biology'),
(5322, 'CSCI', 'Algorithmic Human-Robot Interaction'),
(5340, 'CSCI', 'Startup Essentials: Entrepreneurial Projects in Computing'),
(5350, 'CSCI', 'Entrepreneurial Projects II'),
(5352, 'CSCI', 'Network Analysis and Modeling'),
(5360, 'CSCI', 'Internet Service Provider Networks'),
(5380, 'CSCI', 'Network Virtualization and Orchestration'),
(5402, 'CSCI', 'Research Methods in Human-Robot Interaction'),
(5403, 'CSCI', 'Cybersecurity'),
(5413, 'CSCI', 'Computer Security and Ethical Hacking'),
(5417, 'CSCI', 'Information Retrieval Systems'),
(5423, 'CSCI', 'Biologically-inspired Multi-Agent Systems'),
(5434, 'CSCI', 'Probability for Computer Science'),
(5444, 'CSCI', 'Introduction to Theory of Computation'),
(5446, 'CSCI', 'Chaotic Dynamics'),
(5448, 'CSCI', 'Object-Oriented Analysis and Design'),
(5454, 'CSCI', 'Design and Analysis of Algorithms'),
(5502, 'CSCI', 'Data Mining'),
(5514, 'CSCI', 'Algorithms for Whole Genome Sequence Analysis'),
(5525, 'CSCI', 'Compiler Construction'),
(5535, 'CSCI', 'Fundamental Concepts of Programming Languages'),
(5548, 'CSCI', 'Software Engineering of Standalone Programs'),
(5550, 'CSCI', 'Designing for Defense'),
(5573, 'CSCI', 'Advanced Operating Systems'),
(5576, 'CSCI', 'High-Performance Scientific Computing'),
(5593, 'CSCI', 'Advanced Computer Architecture'),
(5606, 'CSCI', 'Principles of Numerical Computation'),
(5616, 'CSCI', 'Introduction to Virtual Reality'),
(5620, 'CSCI', 'Advanced Wireless Lab'),
(5622, 'CSCI', 'Machine Learning'),
(5630, 'CSCI', 'Wireless and Cellular Systems'),
(5636, 'CSCI', 'Numerical Solution of Partial Differential Equations'),
(5646, 'CSCI', 'Numerical Linear Algebra'),
(5654, 'CSCI', 'Linear Programming'),
(5673, 'CSCI', 'Distributed Systems'),
(5676, 'CSCI', 'Numerical Optimization'),
(5714, 'CSCI', 'Formal Languages'),
(5722, 'CSCI', 'Computer Vision'),
(5753, 'CSCI', 'Computer Performance Modeling'),
(5802, 'CSCI', 'Data Science Team Companion Course'),
(5809, 'CSCI', 'Computer Animation'),
(5817, 'CSCI', 'Database Systems'),
(5822, 'CSCI', 'Probabilistic Models of Human and Machine Learning'),
(5828, 'CSCI', 'Foundations of Software Engineering'),
(5832, 'CSCI', 'Natural Language Processing'),
(5839, 'CSCI', 'User-Centered Design and Development 1'),
(5849, 'CSCI', 'Input, Interaction, and Accessibility'),
(5854, 'CSCI', 'Theoretical Foundations of Autonomous Systems'),
(5880, 'CSCI', 'Interactive Machine Learning for Customizable and Expressive Interfaces')